name: Test on Push and Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install C++ compiler
        run: |
          sudo apt update
          sudo apt install -y g++

      - name: Build and run tests
        run: |
          make test

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0' # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Python tests
        run: |
          cd Testing/E2ETests
          pytest tests.py