name: Test on Push and Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install C++ compiler
        run: |
          sudo apt update
          sudo apt install -y g++

      - name: Build and run tests
        run: |
          make test
