name: Test on Push and Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: liam2258/HuffmanCompAndDecomp/@main
        with:
          compiler: gcc

      - name: Build and run tests
        run: |
          make test
